export const c = {
  ARTIST_INFO_REQUEST: "ARTIST_INFO_REQUEST",
  ARTIST_INFO_SUCCESS: "ARTIST_INFO_SUCCESS",
  ARTIST_INFO_FAILURE: "ARTIST_INFO_FAILURE",

  TOP_TRACKS_REQUEST: "TOP_TRACKS_REQUEST",
  TOP_TRACKS_SUCCESS: "TOP_TRACKS_SUCCESS",
  TOP_TRACKS_FAILURE: "TOP_TRACKS_FAILURE",

  TOP_ARTISTS_REQUEST: "TOP_ARTISTS_REQUEST",
  TOP_ARTISTS_SUCCESS: "TOP_ARTISTS_SUCCESS",
  TOP_ARTISTS_FAILURE: "TOP_ARTISTS_FAILURE"
};
